[package]
name = "breezydb"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.10.2"
tokio = { version = "1", features = [
  "macros",
  "rt",
  "rt-multi-thread",
  "sync",
] }
axum = { version = "0.8.9", features = ["tokio"] }
serde_json = "1"
libsql = { version = "0.9.30", default-features = false, features = ["core"] }

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
debug = 1
